/*
 * AUTOGENERATED FROM PROGRESSIVE-WEBAPP-PLUGIN
 * Injected Global: $LocationMap
 */


 function ServiceWorkerRegister(experimentKey) {
   if (Boolean(navigator.serviceWorker)) {
     if (experimentKey && !$LocationMap[experimentKey]) {
       throw new Error('Experiment: "' + experimentKey + '" not found. Must be one of:', Object.keys($LocationMap).join(', '));
     }
     const key = experimentKey || 'main';
     navigator.serviceWorker.register($LocationMap[key]);
   }
 }

module.exports = {
  register: ServiceWorkerRegister
};
