/*
 * AUTOGENERATED FROM GENERATE-SERVICE-WORKER
 * Injected global: $DEBUG
 */

function print(fn) {
  return function () {
    if ($DEBUG) {
      // eslint-disable-next-line no-console
      console[fn].apply(console, arguments);
    }
  };
}

// eslint-disable-next-line no-unused-vars
const logger = {
  log: print('log'),
  warn: print('warn'),
  error: print('error')
};
