/*
 * AUTOGENERATED FROM GENERATE-SERVICE-WORKER
 * Injected Global: $Notifications, $Log
 */

'use strict';

/*         -------- NOTIFICATIONS CONSTANTS ---------         */

self.addEventListener('push', handleNotificationPush);
self.addEventListener('notificationclick', handleNotificationClick);

/*         -------- NOTIFICATIONS HANDLERS ---------         */

function handleNotificationPush(event) {
  logger.log('Push notification received', event);

  if ($Log.notificationReceived) {
    event.waitUntil(logNotificationReceived(event));
  }

  // Show notification or fallback
  if (event.data && event.data.title) {
    event.waitUntil(showNotification(event.data));
  } else if ($Notifications.fallbackURL) {
    event.waitUntil(
      self.registration.pushManager.getSubscription()
        .then(fetchNotification)
        .then(convertResponseToJson)
        .then(showNotification)
        .catch(showNotification)
    )
  } else {
    logger.warn('No notification.data and no fallbackURL.');
    event.waitUntil(showNotification());
  }
}

function handleNotificationClick(event) {
  logger.log('Push notification clicked.', event.notification);

  if ($Log.notificationClicked) {
    event.waitUntil(logNotificationClick(event));
  }

  // Open the url if provided
  if (event.notification.data && event.notification.data.url) {
    const url = event.notification.data.url;
    event.waitUntil(clients.openWindow(url));
  } else if (event.notification.tag.indexOf(':') !== -1) {
    // TODO: Deprecate
    const url = event.notification.tag.split(':')[2] || '/';
    event.waitUntil(openWindow(url));
  } else {
    logger.warn('Cannot route click with no data.url property. Using "/".');
    event.waitUntil(openWindow('/'));
  }

  event.notification.close();
}

/*         -------- NOTIFICATIONS HELPERS ---------         */

function showNotification(data) {
  if (!data) {
    data = $Notifications.default;
  }
  logger.log('Attempting to show notification: ', data);
  return self.registration
    .showNotification(data.title, data)
    .then(delayDismissNotification);
}

function fetchNotification(subscription) {
  if (!subscription) {
    logger.warn('No subscription found.');
    throw new Error('No subscription found.');
  }
  logger.log('Fetching remote notification data.');
  const queries = {
    endpoint: subscription.endpoint
  };
  const url = formatUrl($Notifications.fallbackURL, queries);
  return fetch(url, { credentials: 'include' });
}

function convertResponseToJson(response) {
  if (response.status !== 200) {
    throw new Error('Notification data fetch failed.');
  }
  return response.json();
}

function delayDismissNotification() {
  if ($Notifications.duration) {
    setTimeout(function serviceWorkerDismissNotification() {
      logger.log('Hiding notification after delay: ', $Notifications.duration);
      self.registration.getNotifications()
        .then(notifs => notifs.forEach(notif => notif.close()));
    }, $Notifications.duration);
  }
}

function openWindow(url) {
  if (clients.openWindow) {
    return clients.openWindow(url);
  }
}

function logNotificationReceived(event) {
  return logAction(event, $Log.notificationReceived);
}

function logNotificationClick(event) {
  return logAction(event.notification, $Log.notificationClicked);
}

function logAction(notification, url) {
  return self.registration.pushManager.getSubscription().then((subscription) => {
    const query = {
      endpoint: subscription.endpoint,
      tag: notification.tag
    };
    return fetch(formatUrl(url, query), { credentials: 'include' });
  });
}

function formatUrl(url, queries) {
  const prefix = url.includes('?') ? '&' : '?';
  const query = Object.keys(queries).map(function (key) {
    return `${key}=${queries[key]}`;
  }).join('&');
  return url + prefix + query;
}

// Export functions on the server for testing
if (typeof __TEST_MODE__ !== 'undefined') {
  module.exports = {
    handleNotificationPush: handleNotificationPush,
    handleNotificationClick: handleNotificationClick,
    showNotification: showNotification,
    delayDismissNotification: delayDismissNotification,
    logNotificationReceived: logNotificationReceived,
    logNotificationClick: logNotificationClick,
    logAction: logAction,
    formatUrl: formatUrl
  };
}
