/*
 * AUTOGENERATED FROM GENERATE-SERVICE-WORKER
 * Injected Global: $Notifications
 */

'use strict';

/*         -------- NOTIFICATIONS CONSTANTS ---------         */

self.addEventListener('push', handleNotificationPush);
self.addEventListener('notificationclick', handleNotificationClick);

if (!$Cache) {
  self.addEventListener('install', (event) => {
    event.waitUntil(self.skipWaiting());
  });
}

/*         -------- NOTIFICATIONS HANDLERS ---------         */

function handleNotificationPush(event) {
  logger.log('Push notification received', event);

  if (event.data && event.data.title) {
    event.waitUntil(showNotification(event.data));
  } else {
    const done = self.registration.pushManager.getSubscription()
      .then(fetchNotificationData)
      .then(handleNotificationResponse)
      .then(showNotification)
      .catch(showNotification.bind(null, $Notifications.default));
    event.waitUntil(done);
  }
}

function handleNotificationClick(event) {
  logger.log('Push notification clicked.', event.notification);

  // Log the click if url provided in config
  if ($Notifications.logClick) {
    event.waitUntil(logNotificationClick(event));
  }

  // Open the url if provided
  if (event.notification.data && event.notification.data.url) {
    const url = event.notification.data.url;
    event.waitUntil(clients.openWindow(url));
  } else {
    const url = event.notification.tag.split(':')[2] || '/';
    event.waitUntil(clients.openWindow(url));
  }

  event.notification.close();
}

/*         -------- NOTIFICATIONS HELPERS ---------         */

/*
 * Use the injected fetch url and append the subscription id as a
 * query parameter.
 */
function fetchNotificationData(subscription) {
  if (!subscription) {
    throw new Error('No subscription found.');
  }
  if (!$Notifications.fetchData) {
    throw new Error('No fetch url provided for notification data.');
  }
  logger.log('Fetching remote notification data for subscription: ', subscription);
  const queries = {
    endpoint: subscription.endpoint,
  };
  const url = formatUrl($Notifications.fetchData.url, queries);
  return fetch(url, $Notifications.fetchData.requestOptions);
}

function handleNotificationResponse(response) {
  if (response.status !== 200) {
    logger.error('Notification data fetch failed. Using default.');
    return $Notifications.default;
  }
  logger.log('Converting remote notification response to JSON.');
  return response.json();
}

function showNotification(data) {
  logger.log('Attempting to show notification: ', data);
  if (data.error) {
    throw new Error(data.error);
  }
  return self.registration
    .showNotification(data.title, data)
    .then(delayDismissNotification);
}

function delayDismissNotification() {
  setTimeout(function serviceWorkerDismissNotification() {
    logger.log('Hiding notification after delay: ', $Notifications.duration);
    self.registration.getNotifications()
      .then(notifs => notifs.forEach(notif => notif.close()));
  }, $Notifications.duration);
}

function logNotificationClick(event) {
  return self.registration.pushManager.getSubscription().then((subscription) => {
    const query = {
      endpoint: subscription.endpoint,
      tag: event.notification.tag,
    };
    const logClickUrl = formatUrl($Notifications.logClick.url, query);
    return fetch(logClickUrl, $Notifications.logClick.requestOptions);
  });
}

function formatUrl(url, queries) {
  const prefix = url.includes('?') ? '&' : '?';
  const query = Object.keys(queries).map(function (key) {
    return `${key}=${queries[key]}`;
  }).join('&');
  return url + prefix + query;
}

// Export functions on the server for testing
if (typeof __TEST_MODE__ !== 'undefined') {
  module.exports = {
    handleNotificationPush: handleNotificationPush,
    fetchNotificationData: fetchNotificationData,
    handleNotificationResponse: handleNotificationResponse,
    showNotification: showNotification,
    delayDismissNotification: delayDismissNotification,
    handleNotificationClick: handleNotificationClick,
    formatUrl: formatUrl,
  };
}
